name: docs

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: abatilo/actions-poetry@v2
      - uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - run: poetry install
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install
      - name: Build website
        run: pnpm doc build -d website
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: website
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        id: deployment
