# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: tests

on:
  push:
    branches: ["main"]
    paths-ignore: ["**.md"]
  pull_request:
    branches: ["main"]
    paths-ignore: ["**.md"]

env:
  CARGO_TERM_COLOR: always

jobs:
  static-jsx:
    concurrency:
      group: ci-test-static-jsx-${{ github.ref }}-${{ matrix.node-version }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/static-jsx

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: tests/static-jsx/pnpm-lock.yaml
      - run: pnpm install
      - name: Install dependencies (typed-htmx)
        run: pnpm install
        working-directory: .
      - name: Build library
        run: pnpm dist
        working-directory: .
      - run: pnpm test
